language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - nvm install node
  - nvm alias default node
  - npm install
before_script:
  - npm run build
  - fab publish
script:
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

