version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.12.0-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "regular/package.json" }}
      - run:
          name: Install npm
          command: npm install
          working_directory: regular
      - run:
          name: Gatsby build
          command: npm run build
          working_directory: regular
      - save_cache:
          key: dependency-cache-{{ checksum "regular/package.json" }}
          paths:
            - regular/node_modules
  test:
    docker:
      - image: circleci/node:8.12.0-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "regular/package.json" }}
      - run:
          name: Install npm
          command: npm install
          working_directory: regular
      - run:
          name: Test
          command: npm test
          working_directory: regular
      - save_cache:
          key: dependency-cache-{{ checksum "regular/package.json" }}
          paths:
            - regular/node_modules
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
